@startuml Game Of Life

package "model" #DDDDDD {
    Class Cell {
        --attributes--
        - alive : boolean
        --methods--
        + toString : String
        ..getter..
        + isAlive : boolean
        ..setter..
        + kill : void
        + spawn : void
    }

    Class Grid {
        --attributes--
        - cells : Cell[1..*]
        --methods--
        + toString : String
        ..getter..
        ..setter..
    }

    Grid "1" --o "*" Cell
}

package GUI {
    Class Observer {}

    Class View {}
}


@end