@startuml Game Of Life

Class Cell {
    --attributes--
    - alive : boolean
    --methods--
    + toString : String
    ..getter..
    + isAlive : boolean
    ..setter..
    + kill : void
    + spawn : void
}

Class Grid {}

Class 

@end